name: Test Code

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: test_code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        run: npm i

      - name: Unit Tests
        run: npm run test

      - name: Unit Test coverage
        run: npm run checkCoverage

      - name: Cypress tests
        uses: cypress-io/github-action@v2.9.7
        with:
          build: npm run build:ci
          start: npm run start
          wait-on: http://localhost:3000
          wait-on-timeout: 120

      - name: Test Cypress coverage
        run: npm run cypress:coverage && npm run checkCypressCoverage

      - name: Linting
        run: npm run lint

      - name: Security audit
        run: npm run npmAudit

      - name: Can module be built
        run: npm run build:ci
